### PR TITLE
add unicode support by u32string

### PR DESCRIPTION
**Pull request by Toudsour**
- Wrap u32string with ustring, in case we will use other implementation in the future

### CODE REVIEW

**Comment by xadupre** [comment]
Do you think this approach is better than using std::wstring?

**Comment by wenbingl** [comment]
> Do you think this approach is better than using std::wstring?

@xadupre 
check this answer: https://stackoverflow.com/questions/4588302/why-isnt-wchar-t-widely-used-in-code-for-linux-related-platforms

**Comment by wenbingl** [comment]
The string tests is great to help the people to understand how to use u32string. 

but I didn't see too much benefit to create a new class ustring, instead of directly using std::u32string.

**Comment by xadupre** [comment]
We should probably update StringNormalizer in onnxruntime https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/nn/string_normalizer.cc#L22 as it is using wstring.

**Comment by Toudsour** [comment]
> The string tests is great to help the people to understand how to use u32string.
> 
> but I didn't see too much benefit to create a new class ustring, instead of directly using std::u32string.

I worry that we will use ICU someday, so I want to wrap it instead of using std::u32string directly. ustring has all the operators of std::u32string, user can use them in the same way with u32string.

**Comment by wenbingl** [comment]
> > The string tests is great to help the people to understand how to use u32string.
> > but I didn't see too much benefit to create a new class ustring, instead of directly using std::u32string.
> 
> I worry that we will use ICU someday, so I want to wrap it instead of using std::u32string directly. ustring has all the operators of std::u32string, user can use them in the same way with u32string.

that's a good justification.

**Comment by wenbingl** [comment]
> We should probably update StringNormalizer in onnxruntime https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/core/providers/cpu/nn/string_normalizer.cc#L22 as it is using wstring.

Wasn't sure if they made the best decision. If it is possible for you check the tensorflow implementation?

**Review by wenbingl — DISMISSED** [review]

**Comment by Toudsour** [comment]
I am sorry that I don't know pushing a new commit require another approval, please help me approve again.

**Review by wenbingl — APPROVED** [review]

**Pull request merged**
